GET http://localhost:3000/deliveries/

###
GET http://localhost:3000/deliveries/deliveryMan/0x2c3e62143fdA1914e9AB7990B21dC556fB2052a2/stage/3

###
GET http://localhost:3000/deliveries/address/0xa5Fa74941F9CbcE75933fE9B025633838EcFe16B

###
POST http://localhost:3000/deliveries/
Content-Type: application/json

{
    "requestId": "testId2",
    "to": "testTo", 
    "from": "testFrom", 
    "item": "testItem", 
    "payment": 100000000000000, 
    "status": "1", 
    "customer": "testCustomer"
}

###

DELETE http://localhost:3000/deliveries/

###
PATCH http://localhost:3000/deliveries/testId
Content-Type: application/json

{
    "status": "2",
    "deliveryMan": "testGuy"
}